# =====================================================
# CONFIGURAÇÕES DE PERSISTÊNCIA (POSTGRESQL)
# =====================================================

# Define o tipo de banco de dados
quarkus.datasource.db-kind=postgresql

# URL de Conexão (Baseada no seu DBeaver: localhost:5432/postgres)
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres

# Credenciais do Banco de Dados (Use suas credenciais reais)
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

# Geração de Esquema (garante que as tabelas sejam criadas e o import.sql rode)
quarkus.hibernate-orm.mapping.jpanamedgeneration=drop-and-create

# Opcional: Para ver o SQL gerado (recomendado para debug)
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.format-sql=true


# =====================================================
# CONFIGURAÇÕES DE SEGURANÇA (Para o Login e 401)
# =====================================================

# Ativa a segurança HTTP
quarkus.http.auth.enabled=true
quarkus.http.auth.basic=true
# Ativa o mecanismo de autenticação por formulário (necessário para o x-www-form-urlencoded)


# Indica que a identidade do usuário será gerenciada pelo seu IdentityProvider (BlogIdentityProvider)
